theme: 
  - osuny-suggestions
  - osuny-campus-art-mediterrannee-footer
  - osuny
_merge: deep
params:
  debug:
    productionUrl: https://www.conservatoiredemarseille.fr
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo.svg'
    footer: '/assets/images/icon.svg'
  home:
    head:
      title: site
  events:
    share_links:
      enabled: false
    index:
      archives: true
      years: true
      group_by_date: "Monday 2 <br>January 2006"
      # sticky_dates: false
    list:
      with_more: true
  pages:
    layouts:
      grid:
        more: true
    index:
      layout: grid
    single:
      taxonomies:
        position: none
  posts:
    single:
      taxonomies:
        show_name: false
        position: hero
  programs:
    index:
      layout: grid
      options:
        image: true
        summary: true
    single:
      taxonomies: 
        show_name: false
      options:
        diploma_certification: false
        logo: false
    share_links:
      enabled: false
  organizations:
    single:
      backlinks: true
  persons:
    single:
      backlinks: true
  image_sizes:
    sections:
      home:
        hero:
          mobile:   400
          tablet:   800
          desktop:  1900
      events:
        children_in_agenda:
          desktop:  539
        layouts:
          agenda:
            mobile:   327
            tablet:   327
            desktop:  539
          list:
            mobile:   327
            tablet:   327
            desktop:  539
      programs:
        layouts:
          grid:
            tablet:   400
            desktop:  539